# Generated by Django 4.2.26 on 2026-02-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0004_aianswer_ailink_questionbank_questionscore_tasklog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='click_count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_light_on',
        ),
    ]
