# Generated by Django 4.2.26 on 2026-04-02 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0005_remove_order_click_count_remove_order_is_light_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                (
                    "relevance_level",
                    models.IntegerField(default=0, verbose_name="相关度等级(0-5)"),
                ),
                (
                    "domain_patterns",
                    models.JSONField(
                        blank=True, default=list, verbose_name="自动匹配域名规则"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6c757d", max_length=20, verbose_name="Treemap显示颜色"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序权重")),
            ],
            options={
                "verbose_name": "信源分类",
                "verbose_name_plural": "信源分类",
                "ordering": ["order", "-relevance_level"],
            },
        ),
        migrations.AddField(
            model_name="ailink",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mvp.linkcategory",
                verbose_name="信源分类",
            ),
        ),
        migrations.AddField(
            model_name="ailink",
            name="is_manual",
            field=models.BooleanField(default=False, verbose_name="是否手动分类"),
        ),
        migrations.AddField(
            model_name="mention_percentage",
            name="high_relevance_ratio",
            field=models.FloatField(default=0, verbose_name="高相关信源占比"),
        ),
        migrations.AddField(
            model_name="mention_percentage",
            name="source_stats",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="信源分类统计快照"
            ),
        ),
        migrations.AddIndex(
            model_name="ailink",
            index=models.Index(
                fields=["category"], name="mvp_ailink_categor_3b31d1_idx"
            ),
        ),
    ]
