# Generated by Django 4.2.26 on 2026-04-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0006_linkcategory_ailink_is_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ailink',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='mvp.aianswer', verbose_name='关联回答'),
        ),
    ]
