# Generated by Django 4.2.26 on 2026-02-09 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remember_me_token', models.CharField(blank=True, max_length=64, null=True, verbose_name='记住我Token')),
                ('remember_me_expires', models.DateTimeField(blank=True, null=True, verbose_name='记住我过期时间')),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='code_type',
            field=models.CharField(choices=[('register', '注册验证码'), ('reset_password', '重置密码验证码')], default='register', max_length=20, verbose_name='验证码类型'),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(max_length=4, verbose_name='验证码'),
        ),
        migrations.AddIndex(
            model_name='emailverificationcode',
            index=models.Index(fields=['email', 'code_type'], name='accounts_em_email_59784a_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationcode',
            index=models.Index(fields=['ip_address', 'created_at'], name='accounts_em_ip_addr_ea451b_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
